image: openjdk:11-slim

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - jar

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  tags:
    - My_Runner
  script:
    - chmod +x ./gradlew
    - ./gradlew compileJava assemble
  artifacts:
    paths:
      - ./User/build/libs/*-1.0.jar
      - ./GpsUtil/build/libs/*-1.0.jar
      - ./RewardCentral/build/libs/*-1.0.jar
      - ./TripPricer/build/libs/*-1.0.jar
      - ./TourGuide/build/libs/*-1.0.jar

integrationTest:
  stage: test
  tags:
    - My_Runner
  image: jtim/docker-docker-compose-jdk:18.09.3-ce-git-compose-1.23.2-adoptopenjdk-11.0.2.9
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker-compose up -d
    - ./gradlew test

jar :
  stage: jar
  tags:
    - My_Runner
  script:
    - chmod +x ./gradlew
    - ./gradlew bootJar assemble
  artifacts:
    paths:
      - ./build/libs/*-1.0.jar
