image: openjdk:11-slim

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - compile
  - build
  - test
  - jar

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

compile:
  stage: compile
  tags:
    - Docker_Runner
  script:
    - chmod +x ./gradlew
    - ./gradlew compileJava assemble

build:
  stage: build
  tags:
    - Docker_Runner
  script:
    - chmod +x ./gradlew
    - ./gradlew --build-cache assemble
  artifacts:
    paths:
      - ./User/build/libs/*-1.0.jar
      - ./GpsUtil/build/libs/*-1.0.jar
      - ./RewardCentral/build/libs/*-1.0.jar
      - ./TripPricer/build/libs/*-1.0.jar
      - ./TourGuide/build/libs/*-1.0.jar

test:
  stage: test
  tags:
    - Docker_Runner
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - chmod +x ./gradlew
    - ./gradlew test --tests '*Test'

jar :
  stage: jar
  tags:
    - Docker_Runner
  script:
    - chmod +x ./gradlew
    - ./gradlew bootJar assemble
  artifacts:
    paths:
      - ./build/libs/*-1.0.jar