version: "3.3"
services:
#  CommonSet:
#    build: ./CommonSet/.
#    image: microservice-commonset
#    ports:
#      - "7070:7070"
#    container_name: "microservice-commonset"

  TourGuide:
    image: tourguide-app
    ports:
      - "8080:8080"
    container_name: "tourguide-app"

  User:
    image: microservice-user
    ports:
      - "8181:8181"
    container_name: "microservice-user"

  GpsUtil:
    image: microservice-gpsutil
    ports:
      - "8282:8282"
    container_name: "microservice-gpsutil"

  RewardCentral:
    image: microservice-rewardcentral
    ports:
      - "8383:8383"
    container_name: "microservice-rewardcentral"

  TripPricer:
    image: microservice-trippricer
    ports:
      - "8484:8484"
    container_name: "microservice-trippricer"