#version: "3.9"
#
#services:
#    TourGuide:
#      build: ./TourGuide
#      ports:
#        - "localhost:8080"
#      container_name: "TourGuide"
#
#    Users:
#      build: ./User
#      ports:
#      - "localhost:8282"
#    container_name: "User"
#
#      GpsUtil:
#        build: ./GpsUtil
#        ports:
#          - "localhost:8383"
#        container_name: "GpsUtil"
#
#    RewardCentral:
#      build: ./RewardCentral
#      ports:
#        - "localhost:8484"
#      container_name: "RewardCentral"
#
#    TripPricer:
#      build: ./TripPricer
#      ports:
#        - "localhost:8585"
#      container_name: "TripPricer"