# FROM openjdk:11-jdk-slim
#
# ARG JAR_FILE=./build/libs/TourGuide-0.0.1-SNAPSHOT.jar
#
# COPY ${JAR_FILE} TourGuide.jar
#
# ENV SPRING_PROFILES_ACTIVE=docker
#
# ENTRYPOINT ["java", "-jar", "/TourGuide.jar"]