# FROM openjdk:11-jdk-slim
#
# ARG JAR_FILE=./build/libs/RewardCentral-0.0.1-SNAPSHOT.jar
#
# COPY ${JAR_FILE} RewardCentral.jar
#
# ENV SPRING_PROFILES_ACTIVE=docker
#
# ENTRYPOINT ["java", "-jar", "/RewardCentral.jar"]